openapi: 3.0.0
info:
  version: 1.0.0
  title: Calculator
  description: Calculator API implementation

paths: 
  /api/fast/{op}/{arg1}/{arg2}:
  
    parameters:
        - in: path
          name: op  
          required: true
          schema:
            type: number
            format: integer
          description: Type of fast opearion
        - in: path
          name: arg1   
          required: true
          schema:
            type: number
            format: double
          description: Argument for fast operation
        - in: path
          name: arg2   
          required: true
          schema:
            type: number
            format: double
          description: Argument for fast operation
            
    get:
      description: Get result for fast operation
      operationId: resultFastOp
      responses:
        200:
          description: Successful result
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: number
                    format: double
                    description: Result
                    
        400:
          description: Can't get the result
          
        405:
          description: No such operation
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    codeOp:
                      type: integer
                      
                    operation:
                      type: string
                      description: Type of operation (+-*/)
                      
          
  /slow/{op}/{arg}:
    parameters:
        - in: path
          name: op  
          required: true
          schema:
            type: integer
          description: Type of slow operation
        - in: path
          name: arg   
          required: true
          schema:
            type: number
            format: double
          description: Argument for slow operation
          
    get:
      description: Get result for slow operation
      operationId: resultSlowOp
      responses:
        200:
          description: Successful result
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: number
                    format: double
                    description: Result
                    
        400:
          description: Can't get the result
          
        405:
          description: No such operation
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    codeOp:
                      type: integer
                      
                    operation:
                      type: string
                      description: Type of operation (sqrt,!)
        425:
          description: The result is calculated 
        
        408:
          description: Timeout
    
    put:
      description: New slow operation
      operationId: newSlowOp
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                time:
                  type: number
                  format: double
                  
      responses:
        200:
          description: Successful adding
        400:
          description: Unsuccessful adding